### ISSUE TITLE
5.0 Roadmap

### ISSUE THREAD

**Issue by AsakuraMizu** [Harry-Chen/Learn-Helper#147]
General:
- [ ] 与 thu-learn-lib 合并为 monorepo

Service:
- [ ] 后台服务 & 新内容提醒 (需要将目前的数据更新逻辑与前端分离)
- [ ] 支持更多网络学堂新功能 (已读/星标/备注/#143)
- [ ] 跨设备/浏览器状态同步
- [ ] #119 

UI:
- [ ] 路由化
- [ ] Preact
- [ ] 提交作业页面
- [ ] ~~发 major 怎么能不改 ui 呢~~

**Comment by AsakuraMizu** [comment]
目前预想的新功能需要改动大量代码，不管是逻辑（如后台刷新）还是界面（如同时维护多学期、文件分类）和现在的设计都有很大出入。在 https://github.com/Harry-Chen/Learn-Helper/tree/next 上初步实现了一些迁移，不是很理想，考虑对大部分代码进行重写。
